### ISSUE TITLE
amxx galileo and voted nextmap

### ISSUE THREAD

**Issue by fred0r** [s1lentq/ReGameDLL_CS#214] opened 2017-11-13 01:45 UTC
Linux:
reHLDS:: 3.3.0.605-dev
reGameDLL_cs: 5.3.0.269
metamod-p: v37 compiled: May 30 2013, 11:41:16 EET (optimized)
amxx: AMX Mod X 1.8.3-dev+5144
+ reAPI: ReAPI 5.2.0.136- (Asmodai & s1lent     running)
+ galileo (https://forums.alliedmods.net/showthread.php?p=684848)

The in-game voted (and announced) nextmap doesnt start - but the nextmap from the mapcycle.txt

**Comment by In-line** [comment] 2017-11-13 03:59
Does this happen with stock gamedll?

**Comment by In-line** [comment] 2017-11-13 04:21
Galileo issue tracker: https://github.com/evandrocoan/MultiModServer/issues

**Comment by fred0r** [comment] 2017-11-13 13:12
The Plugin work with the orig. gamedll.

**Comment by In-line** [comment] 2017-11-13 13:21
Update Galileo

**Comment by In-line** [comment] 2017-11-16 16:42
Seems to be duplicate of #213 . Closing for now. If updating Galileo will not help, than I'll reopen issue.

**Closed by In-line** 2017-11-16 16:42 UTC
Labels: help wanted

**Comment by fred0r** [comment] 2017-11-18 00:25
Updated galileo to your mentioned version and now everything works.
thank you.
