### ISSUE TITLE
Does ReGameDLL_CS (or ReHlds) bugfixed fix an old accuracy bug ?

### ISSUE THREAD

**Issue by Freeman-AM** [s1lentq/ReGameDLL_CS#138] opened 2017-04-16 09:35 UTC
Here is the bug i mention :
https://forums.alliedmods.net/showthread.php?p=1549133?p=1549133
Is it fixed in ReGameDLL_CS (or ReHlds) or do I still need the plugin to fix it ?
Thanks

**Comment by WPMGPRoSToTeMa** [comment] 2017-04-16 19:21
Nope. This is the duplicate of https://github.com/s1lentq/ReGameDLL_CS/issues/88.

**Closed** 2017-11-05 20:34 UTC
Labels: duplicate
